apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satishnaga1/crossplane-aws.git
    targetRevision: HEAD
    path: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
