apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: sample-instance1
spec:
  forProvider:
    region: ap-south-1
    ami: ami-faf12191aa3337
    instanceType: t2.nano
    blockDeviceMappings:
     - deviceName: /dev/sdx
       ebs:
         volumeSize: 4
    subnetIdRef:
      name: sample-subnet
  providerConfigRef:
    name: default
