apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: sample-vpc2
spec:
  forProvider:
    region: us-east-1            # Replace with your AWS region
    cidrBlock: 10.0.0.0/16
  providerConfigRef:
    name: aws-provider           # Must match your ProviderConfig name

