name: Deploy Crossplane AWS Resources (Windows Self-Hosted)

on:
  push:
    paths:
      - 'crossplane/*.yaml'
      - '.github/workflows/deploy-crossplane.yaml'
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print workspace path and files
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: |
          Write-Host "Repo checked out at: $env:GITHUB_WORKSPACE"
          Get-ChildItem -Recurse -Path "$env:GITHUB_WORKSPACE\crossplane"

      - name: Apply ProviderConfig
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\providerconfig.yaml"

      - name: Apply VPC
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\vpc.yaml"
      - name: Wait for VPC to be Ready
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl wait --for=condition=Ready vpc.ec2.aws.crossplane.io/sample-vpc2 --timeout=180s

      - name: Apply Subnet
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\subnet.yaml"
