name: Deploy Crossplane AWS Resources (Windows Self-Hosted)

on:
  push:
    paths:
      - 'crossplane/*.yaml'
      - '.github/workflows/deploy-crossplane.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - Print GITHUB_WORKSPACE and crossplane files
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: |
          Write-Host "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          if (Test-Path "$env:GITHUB_WORKSPACE\crossplane") {
            Write-Host "Contents of crossplane directory:"
            Get-ChildItem "$env:GITHUB_WORKSPACE\crossplane"
          } else {
            Write-Error "❌ Directory not found: $env:GITHUB_WORKSPACE\crossplane"
            exit 1
          }

      - name: Apply ProviderConfig
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\providerconfig.yaml"

      - name: Apply VPC
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\vpc.yaml"

      - name: Wait for VPC to be Ready
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl wait --for=condition=Ready vpc.ec2.aws.crossplane.io/sample-vpc2 --timeout=180s

      - name: Apply Subnet
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\subnet.yaml"
