name: Deploy Crossplane AWS Resources

on:
  push:
    paths:
      - 'crossplane/providerconfig.yaml'
      - '.github/workflows/deploy-crossplane.yaml'

  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted  # use your self-hosted runner label

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # If kubectl already installed on runner, skip this step
      - name: Setup kubectl (optional)
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # If your runner already has kubeconfig configured, skip this step
      # Otherwise, uncomment below to setup kubeconfig from secret
      #- name: Setup KUBECONFIG
      #  run: |
      #    mkdir -p ~/.kube
      #    echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
      #    chmod 600 ~/.kube/config

      - name: Show working directory and Crossplane files
        run: |
          Get-Location
          Get-ChildItem -Recurse -Path crossplane
        shell: powershell
      - name: Apply VPC
        run: kubectl apply -f crossplane\vpc.yaml
        shell: powershell
     
