name: Deploy Crossplane AWS Resources (Windows Self-Hosted)

on:
  push:
    paths:
      - 'crossplane/*.yaml'
      - '.github/workflows/deploy-crossplane.yaml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted # Adjust label if you used something else

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print workspace path and files
        
        run: |
          Write-Host "Repo checked out at: $env:GITHUB_WORKSPACE"
          Get-ChildItem -Recurse -Path "$env:GITHUB_WORKSPACE\crossplane"

      - name: Apply ProviderConfig
        
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\providerconfig.yaml"

      - name: Apply VPC
        
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\vpc.yaml"

      - name: Apply Subnet
        
        run: kubectl apply -f "$env:GITHUB_WORKSPACE\crossplane\subnet.yaml"
