name: Deploy Crossplane Resources

on:
  push:
    paths:
      - 'crossplane/**'
  workflow_dispatch:     

jobs:
  deploy:
    runs-on: self-hosted  # Windows 11 self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show working directory and files
        run: |
          cd
          dir crossplane
        shell: cmd

      - name: Apply ProviderConfig
        run: kubectl apply -f crossplane\providerconfig.yaml
        shell: cmd

      - name: Apply VPC
        run: kubectl apply -f crossplane\vpc.yaml
        shell: cmd
