name: Deploy Crossplane AWS Resources (Windows Self-Hosted)

on:
  push:
    paths:
      - 'crossplane/*.yaml'
      - '.github/workflows/deploy-crossplane.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - Print current directory and crossplane files
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: |
          Write-Host "Current directory:"
          pwd
          if (Test-Path ".\crossplane") {
            Write-Host "Contents of crossplane directory:"
            Get-ChildItem .\crossplane
          } else {
            Write-Error "❌ Directory not found: .\crossplane"
            exit 1
          }

      - name: Apply ProviderConfig
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f .\crossplane\providerconfig.yaml

      - name: Apply VPC
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f .\crossplane\vpc.yaml

      - name: Check VPC status
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl get vpc.ec2.aws.crossplane.io

      - name: Wait for VPC to be Ready
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl wait --for=condition=Ready vpc.ec2.aws.crossplane.io/sample-vpc1 --timeout=180s

      - name: Apply Subnet
        shell: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -Command {0}"
        run: kubectl apply -f .\crossplane\subnet.yaml
